export const uiId = {
  common: {
    scroll: "Scroll",
    seeMore: "Lihat selengkapnya",
    activeUsers: "pengguna aktif",
    allRightsReserved: "All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    toggleMenu: "Toggle menu",
    startWith: "Mulai dengan",
    viewAiEcosystem: "Lihat ekosistem AI",
    openPage: "Buka halaman",
  },
  navbar: {
    signIn: "Masuk",
    getStarted: "Mulai Sekarang",
  },
  footer: {
    navigation: "Navigasi",
    products: "Produk",
    contact: "Kontak",
  },
  hero: {
    badge: "Penyedia Produk AI & Platform SaaS Terdepan di Indonesia",
    exploreProducts: "Jelajahi Produk",
    contactUs: "Hubungi Kami",
    subtitleSuffix: "untuk kreator, bisnis, dan individu.",
  },
  intro: {
    badge: "Tentang Kami",
    title: "Penyedia Produk Kecerdasan Buatan untuk Bisnis Modern",
    body: "Kami mengembangkan dan mengoperasikan ekosistem produk kecerdasan buatan (AI) dan platform berbasis langganan (SaaS) yang membantu pebisnis, UMKM, tim kreatif, marketer, perusahaan, dan semua kalangan bekerja lebih cepat dan lebih cerdas.",
    bullets: ["5+ platform SaaS siap pakai", "5.000+ pengguna aktif", "Dukungan 24/7"],
    learnMore: "Pelajari tentang kami",
  },
  cta: {
    headline: "Siap Mulai Berlangganan?",
    body: "Bergabung dengan ribuan pengguna yang sudah berlangganan",
    bodySuffix: "untuk produk kecerdasan buatan mereka.",
    startNow: "Mulai Sekarang",
  },
  services: {
    badge: "Platform",
    previewTitle: "Platform Unggulan",
    fullTitle: "Ekosistem Platform SaaS",
    previewDesc: "Cuplikan platform kecerdasan buatan kami. Detail lengkap tersedia di halaman Platform.",
    fullDesc: "Lima platform berbasis langganan (SaaS) — dari konten kreatif, video AI, hingga CRM penjualan.",
    allPlatforms: "Semua platform",
  },
  servicesProcess: {
    badge: "Proses",
    title: "Cara Memulai",
    description: "Alur berlangganan yang sederhana — dari trial gratis hingga dukungan berkelanjutan.",
  },
  features: {
    badge: "Keunggulan",
    title: "Mengapa Memilih Giga Vertex?",
    description: "Kami menggabungkan teknologi AI terdepan dengan desain premium untuk memberikan pengalaman terbaik.",
    metrics: {
      aiProcessing: "AI Processing",
      userSatisfaction: "User Satisfaction",
      platformUptime: "Platform Uptime",
    },
    quote: "Platform kami dirancang untuk skala — dari startup hingga enterprise, dengan infrastruktur yang handal dan support yang responsif.",
    quoteAttribution: "— Product Team, Giga Vertex",
  },
  products: {
    badge: "Produk",
    previewTitle: "Portofolio Produk SaaS",
    fullTitle: "Ekosistem Produk SaaS AI",
    previewDesc: "Autonix, Terabyte, Giga, Newton AI, dan Growi — platform SaaS andalan kami dengan ribuan pengguna aktif.",
    fullDesc: "Lima platform SaaS AI & CRM untuk creator, bisnis, dan agency — dari konten, video, hingga penjualan. Sudah dipercaya ribuan pengguna.",
    allProducts: "Semua produk",
    interfaceAlt: "Antarmuka",
    comingSoonLabel: "Segera hadir",
  },
  ai: {
    videoAriaLabel: "Video ekosistem kecerdasan buatan Giga Vertex",
    viewProducts: "Lihat Produk AI",
    tryFree: "Coba Gratis",
    capabilitiesBadge: "Kemampuan",
    capabilitiesTitle: "Teknologi di Balik Platform Kami",
    capabilitiesDesc: "Spektrum kecerdasan buatan yang menggerakkan setiap produk SaaS dalam ekosistem Giga Vertex.",
    ecosystemBadge: "Ekosistem",
    ecosystemTitle: "Ekosistem Produk SaaS AI",
    ecosystemDesc: "Autonix, Terabyte, Giga, Newton AI, dan Growi — fondasi Growth Ecosystem kami.",
    useCaseBadge: "Use case",
    useCaseTitle: "AI untuk Siapa?",
    useCaseDesc: "Setiap platform SaaS kami dirancang untuk kebutuhan pengguna di berbagai skala.",
    techBadge: "Teknologi",
    techTitle: "Pendekatan Teknis",
    productsBadge: "Produk",
    productsTitle: "Portofolio Produk SaaS",
    productsDesc: "Autonix, Terabyte, Giga, Newton AI, dan Growi — platform subscription aktif dalam ekosistem Giga Vertex.",
    processBadge: "Proses",
    processTitle: "Cara Memulai Berlangganan",
    whyBadge: "Keunggulan",
    whyTitle: "Mengapa Giga Vertex?",
    viewRoadmap: "Lihat roadmap 2026+",
    homeTitle: "Ekosistem AI untuk Semua Kalangan",
    homeDesc: "Platform berbasis langganan (SaaS) untuk generative AI, LLM, automasi, dan CRM — Autonix, Terabyte, Giga, Newton AI, dan Growi dengan ribuan pengguna aktif.",
    learnAi: "Pelajari kecerdasan buatan",
  },
  contact: {
    badge: "Kontak",
    title: "Hubungi Kami",
    description: "Punya pertanyaan, ingin demo produk, atau butuh bantuan berlangganan? Tim kami siap membantu Anda.",
    homeDescription: "Punya pertanyaan, ingin demo produk, atau diskusi kerjasama? Tim kami siap membantu.",
    phoneLabel: "Telepon / WA",
    hoursLabel: "Jam Operasional",
    hoursValue: "Senin - Jumat, 09:00 - 18:00 WIB",
    addressLabel: "Alamat",
    emailLabel: "Email",
    fullName: "Nama Lengkap",
    email: "Email",
    subject: "Subjek",
    message: "Pesan",
    subjectPlaceholder: "Demo Produk / Berlangganan",
    messagePlaceholder: "Ceritakan produk yang ingin Anda coba atau kebutuhan berlangganan Anda...",
    send: "Kirim Pesan",
    sentTitle: "Pesan Terkirim!",
    sentDesc: "Terima kasih! Tim kami akan menghubungi Anda segera.",
    sendForm: "Kirim pesan / formulir kontak",
    goToContact: "Ke halaman kontak",
  },
  market: {
    badge: "Pasar",
    title: "Hadir untuk Pasar Lokal & Global",
    description: "Strategi ekspansi bertahap — dari Indonesia dan Asia Tenggara, ke pasar berbahasa Inggris, hingga Eropa.",
    detailLink: "Detail jangkauan pasar",
  },
  roadmap: {
    homeTitle: "Roadmap Growth Ecosystem 2026+",
    homeDesc: "Dari fondasi Indonesia & ASEAN hingga ekspansi global — perkiraan fase pertumbuhan ekosistem.",
    fullLink: "Lihat roadmap lengkap",
    growthPhasesTitle: "Fase Pertumbuhan 2026+",
    growthPhasesDesc: "Perkiraan bulan dan tahun agar mudah dibaca — dari fondasi domestik hingga visi global.",
  },
  ads: {
    homeTitle: "Meta, TikTok & Google Ads",
    homeDesc: "Tiga kanal akuisisi pelanggan — terukur, scalable, selaras roadmap pertumbuhan.",
    detailLink: "Detail strategi iklan",
  },
  pricing: {
    faqBadge: "FAQ",
    faqTitle: "Pertanyaan Umum",
    faqDesc: "Jawaban singkat seputar paket berlangganan dan platform kecerdasan buatan kami.",
  },
  career: {
    whyBadge: "Mengapa Kami",
    benefitsBadge: "Benefit",
    openingsBadge: "Lowongan",
    processBadge: "Proses",
    applyNow: "Lamar Sekarang",
  },
  about: {
    leadershipBadge: "Kepemimpinan",
    leadershipTitle: "Founder & CEO",
    leadershipDesc: "Visi dan arah penyedia produk kecerdasan buatan dan platform SaaS Giga Vertex Technology.",
    growthVideoLabel: "Growth Ecosystem — video pertumbuhan bisnis",
    missionIllustrationLabel: "Ilustrasi misi perusahaan",
  },
  pages: {
    about: { title: "Tentang Kami", description: "Pelajari lebih lanjut tentang PT Giga Vertex Technology — penyedia produk kecerdasan buatan (AI), perangkat lunak, dan platform berbasis langganan (SaaS)." },
    contact: { title: "Kontak", description: "Hubungi PT Giga Vertex Technology — email, telepon, atau kirim pesan langsung melalui form kontak." },
    services: { title: "Platform", description: "Platform kecerdasan buatan (SaaS) PT Giga Vertex Technology — produk kreatif, automasi sosial media, video AI, CRM, dan multi-model studio." },
    products: { title: "Produk", description: "Ekosistem produk SaaS Giga Vertex — Autonix, Terabyte, Giga, Newton AI, dan Growi untuk konten, video AI, dan CRM." },
    ai: { title: "Kecerdasan Buatan", description: "Ekosistem kecerdasan buatan PT Giga Vertex Technology — generative AI, LLM, automasi, dan platform berbasis langganan (SaaS) untuk semua kalangan." },
    pricing: { title: "Harga", description: "Paket berlangganan fleksibel Giga Vertex — Starter, Professional, dan Enterprise untuk setiap kebutuhan." },
    roadmap: { title: "Roadmap", description: "Roadmap Growth Ecosystem 2026+ Giga Vertex — timeline, pilar, dan visi global." },
    market: { title: "Pasar", description: "Jangkauan pasar Giga Vertex — Indonesia, ASEAN, Amerika, Oseania, Inggris, dan Eropa." },
    ads: { title: "Strategi Iklan", description: "Strategi Meta Ads, TikTok Ads, dan Google Ads Giga Vertex — mesin akuisisi pelanggan." },
    career: { title: "Karier", description: "Bergabung dengan PT Giga Vertex Technology — lowongan kerja di produk AI, engineering, design, marketing, dan operasional." },
    servicesPageHeader: "Platform SaaS Kami",
    servicesPageDesc: "Ekosistem produk kecerdasan buatan berbasis langganan (SaaS) — langsung pakai, bayar bulanan, tanpa setup rumit.",
    productsPageHeader: "Produk & Platform SaaS",
    productsPageDesc: "Lima platform SaaS dalam satu ekosistem — sudah dipercaya ribuan pengguna dari creator hingga tim bisnis.",
    pricingPageHeader: "Paket & Harga",
    pricingPageDesc: "Pilih paket yang tepat. Upgrade atau downgrade kapan saja.",
  },
} as const;

export function getUi() {
  return uiId;
}
